### ISSUE TITLE
Make Abi serializable

### ISSUE THREAD

**Issue by blessedbythestorm** [FelipeRosa/rust-ethereum-abi#52]
I would like to serde serialize/deserialize my own struct that holds the ethereum_abi::Abi struct. 

I would like to serialize the whole thing to write the Abi as a string to my database and then deserialize it into a matching struct when read from the database. 

Currently this limitation forces me to do Abi::from_str every time I want to decode an input.

```
error[E0277]: the trait bound `Abi: firestore_data::_::_serde::Serialize` is not satisfied
    --> src\firestore_data.rs:33:5
     |
33   |     pub abi_struct: Abi,
     |     ^^^ the trait `firestore_data::_::_serde::Serialize` is not implemented for `Abi`
     |
note: required by a bound in `firestore_data::_::_serde::ser::SerializeStruct::serialize_field`
    --> C:\Users\Stormblessed\.cargo\registry\src\github.com-1ecc6299db9ec823\serde-1.0.136\src\ser\mod.rs:1899:12
     |
1899 |         T: Serialize;
     |            ^^^^^^^^^ required by this bound in `firestore_data::_::_serde::ser::SerializeStruct::serialize_field`
```

At the moment it seems the struct is only deserializable.
Forgive my ignorance if there is any known limitation to this at the moment.

**Comment by FelipeRosa** [comment]
Hey @limpit666,

this is because I wanted the `Abi` to be parsed only from a JSON file. I guess having it implement `Deserialize` is misleading as it implies it could be deserialized from any format serde supports.

What kind of format were you thinking about for serializing the `Abi` struct (seems like it's JSON)?

**Comment by blessedbythestorm** [comment]
Hi @FelipeRosa, thanks for the prompt response.

Yes, JSON would do it for me. Guess it would make sense that ABI is serializable back into JSON, I usually fetch it from the etherscan API and it already comes in this format (unsure if the ethereum ABI design meant it to be compatible with JSON on purpose from the start? Kinda assuming it was.) 

I am currently working with a Firestore crate that takes a serializable struct and serializes it into a JSON that then gets matched with the Firestore value types and stored as a Firestore document. I would like to be able to store/fetch ABI's without having to manually convert the data to a string beforehand. Currently I am having to support 2 different structs, one with the whole ABI as a string and one with the instance of the etherscan_abi::from_str() to allow this functionality.

Hope that makes my intentions clearer.

**Comment by FelipeRosa** [comment]
> Hope that makes my intentions clearer.
Absolutely :).

> Guess it would make sense that ABI is serializable back into JSON, I usually fetch it from the etherscan API and it already comes in this format (unsure if the ethereum ABI design meant it to be compatible with JSON on purpose from the start? Kinda assuming it was.)

I found it out here: https://docs.soliditylang.org/en/v0.8.12/abi-spec.html#json. I'm not sure either if it is a standard or not.

I'm inclined to agree I could make it serializable/deserializable so it would be up to the lib user to choose which format to use. I'll come up with something.

**Comment by FelipeRosa** [comment]
@limpit666,

I implemented `Serialize` (#55) for the `Abi` type so you should be able to use it now. Just released a version (0.4.0) which you can update to get the new feature.

I also removed the `Abi::from_str` implementation so it is a breaking change (albeit a small one I think).

Let me know if all went well :)

**Comment by limpit666** [comment]
Just did the appropriate changes in my code, works like a charm!
Thanks for maintaining this awesome lib!

**Comment by blessedbythestorm** [comment]
Just did the appropriate changes in my code, works like a charm!
Thanks for maintaining this awesome lib!
