### ISSUE TITLE
ABI `"type": "error"` is not supported in main branch

### ISSUE THREAD

**Issue by c0mm4nd** [FelipeRosa/rust-ethereum-abi#62]
e.g. ABI from https://etherscan.io/token/0x00000000000001ad428e4906aE43D8F9852d0dD6#code
which contains:
```
      {
        "inputs": [],
        "name": "BadContractSignature",
        "type": "error"
      },
      {
        "inputs": [],
        "name": "BadFraction",
        "type": "error"
      },
```

serde_json::from_str will panic on each `"type": "error"`

**Comment by FelipeRosa** [comment]
Added in this PR: https://github.com/FelipeRosa/rust-ethereum-abi/pull/63.

I'll release a new version soon.
